### ISSUE TITLE
Device bug in huggingface implementation of ViT-L-native

### ISSUE THREAD

**Issue by Parskatt** [apple/ml-aim#12]
See here: https://huggingface.co/apple/aimv2-large-patch14-native/blob/main/modeling_aimv2.py#L26

This seems to have been translated from here: https://github.com/apple/ml-aim/blob/main/aim-v1/aim/v1/torch/layers.py#L34

But the GitHub implementation is a nn.Module, so casting the module to correct device works. For the huggingface implementation it's a function, so breaks.

**Comment by michalk8** [comment]
Thank you for noticing this, fixed [here](https://huggingface.co/apple/aimv2-large-patch14-native/commit/df5cf3a3f388283b723e4e3f71eff8f69c154f1a).
