### ISSUE TITLE
Weights for zero shot detection and VQA model

### ISSUE THREAD

**Issue by harpreetsahota204** [apple/ml-aim#23]
Hi,

Your paper mentions performance on zero-shot detection and VQA tasks,but I don't see those weights on HF. Is there any plan to release those fine-tuned models or is that a task left to the GPU poor 😝

**Comment by aelnouby** [comment]
Thanks @harpreetsahota204 for your question. At the moment, there are no plans to release weights for any modules other than for the image encoder.
